apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: testhttpd
  namespace: argocd
spec:
  project: sandbox
  source:
    path: testhttpd
    repoURL: https://github.com/neco-test/apps-sandbox
  destination:
    namespace: maneki
    server: https://kubernetes.default.svc
